# Generated by Django 5.2 on 2025-04-27 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FinTech", "0007_alter_expense_date_alter_income_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(default=datetime.date(2025, 4, 27)),
        ),
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateField(default=datetime.date(2025, 4, 27)),
        ),
    ]
